# Generated by Django 4.2.3 on 2023-07-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('national', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.PositiveIntegerField()),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_type', models.CharField(max_length=100)),
                ('preferred_job', models.CharField(max_length=250)),
                ('job_city', models.CharField(choices=[('Barisal', 'Barisal'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Chattogram', 'Chattogram'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka')], max_length=100)),
                ('linkedin', models.FileField(blank=True, upload_to='linkedinfile')),
                ('profile', models.ImageField(blank=True, upload_to='profileimage')),
                ('my_file', models.FileField(blank=True, upload_to='resumefile')),
            ],
        ),
    ]
