# Generated by Django 4.2.3 on 2023-07-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumemodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='pin',
        ),
    ]
