# Generated by Django 4.2.3 on 2023-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_resumemodel_city_remove_resumemodel_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=100),
        ),
    ]
