# Generated by Django 4.2.3 on 2023-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_resumemodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
